spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/health_project_data
      username: root
      password: lzn123

server:
  port: 80

mybatis-plus:
  
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
